---
title: "Sobre nosotras"
---

Esta sesi칩n promueve la reproducibilidad del c칩digo, la buena documentaci칩n del c칩digo y buenas pr치cticas para generar un mejor futuro en la ciencia con acceso libre a la informaci칩n. Siendo parte del [Reprohack2024](https://github.com/R-Ladies-Morelia/Reprohack2024) de R-Ladies Morelia.

## Grupo 2: ggplot y variantes gen칠ticas

El art칤culo seleccionado tiene como idea principal investigar c칩mo la selecci칩n por fagos afecta la **evoluci칩n de la resistencia en bacterias**, espec칤ficamente en *Pseudomonas syringae*. Los autores se centran en estudiar si la **sensibilidad a los fagos puede reaparecer** cuando ya no est치n presentes (es decir, cuando la presi칩n selectiva disminuye). Para ello, rastrean la evoluci칩n de la **resistencia a lo largo del tiempo** y descubren que, en la mayor칤a de los casos, las bacterias no vuelven a ser sensibles. Adem치s, examinan c칩mo las **mutaciones compensatorias** pueden influir en este proceso.

Aqu칤 puedes encontrar el art칤culo completo: [Historical contingency drives compensatory evolution and rare reversal of phage resistance](https://academic.oup.com/mbe/article/39/9/msac182/6673247)

## Integrantes

- Amairani Cancino Bello, Estudiante de doctorado, Cinvestav-IPN
- Mar칤a Jos칠 Palma Mart칤nez
- Evelia Coss, LIIGH-UNAM, [correo](ecoss@liigh.unam.mx), [pagina web](https://eveliacoss.github.io/)
- Sofia Zorrilla
- Maribel Arenas
- Mayra Fragoso
- Aline Cazares, Estudiante de Maestr칤a, CINVESTAV-IPN

-----------------------------
Cursos hechos con amor 游눞
